### PR TITLE
2020 paradigm

### PR DESCRIPTION
**Pull request by SaltyJoke**
I'm requesting merge so that the explanation of the code structure can get onto the website without waiting for the training part.

### CODE REVIEW

**Comment by SaltyJoke** [comment]
.. I just realized that a little piece of training I did got included in there. Is there a way to delete that commit?

**Comment by kevinzwang** [comment]
> .. I just realized that a little piece of training I did got included in there. Is there a way to delete that commit?

@SaltyJoke which commit is it? Or is it only part of a commit?

**Comment by kevinzwang** [comment]
And why is it all in `TrainingBot-Imported`?

**Comment by SaltyJoke** [comment]
"Make 2020 version of TrainingRobot" is me doing the training. Looks like it also put in some automatic changes when importing a 2019 project into 2020 wpilib VS code.

**Pull request closed without merging**
