### PR TITLE
Update code, tutorials, links, and grammar

### PR DESCRIPTION
**Pull request by SaltyJoke**
My compiler didn't like wpilib2 again, and I don't remember how this problem was fixed last year, so I can't perfectly check the correctness of my code. GitHub says my code doesn't compile, so can you look into it please? 

Also should we add spark maxes to the multiple motors part of the training?

### CODE REVIEW

**Comment by SaltyJoke** [comment]
Should we add all of the configureButtonBindings functions in RobotContainer so that trainees can use the buttons on the joysticks?

**Review by brettle — APPROVED** [review]
Nice work. Good to merge.

**Comment by brettle** [comment]
> Should we add all of the configureButtonBindings functions in RobotContainer so that trainees can use the buttons on the joysticks?

I don't understand the question. Can you propose it as a separate Pull Request so I can see what you mean?

**Comment by SaltyJoke** [comment]
I'll make a pull request later showing all of the things I'm unsure of.

**Pull request merged**
